from typing import Any, Dict
from llama_index.core.tools import FunctionTool
from tavily import AsyncTavilyClient
from configs import TAVILY_API_KEYS


# Tavily 비동기 클라이언트 초기화
_tavily_client = AsyncTavilyClient(api_key=TAVILY_API_KEYS)


async def _search_web(query: str, max_results: int = 5) -> Dict[str, Any]:
    try:
        result = await _tavily_client.search(
            query=query,
            max_results=max_results,
            include_answer=True,
            include_raw_content=False,
        )
        return result

    except Exception as e:
        return {
            "error": f"Failed to query Tavily API: {e}"
        }




# ==============================================================================================================
search_web = FunctionTool.from_defaults(
    fn=_search_web,
    name="search_web",
    description=(
        "Asynchronously search the web using the Tavily API and return a structured response "
        "containing up-to-date, relevant information for the query.\n\n"
        "Use this when the locally available project context is insufficient and you need "
        "concise background details about frameworks, libraries, or best practices to "
        "enrich README content.\n\n"
        "The result typically includes:\n"
        "  - 'answer': A concise natural-language summary generated by Tavily\n"
        "  - 'results': A list of search hits containing titles, URLs, and snippet summaries\n\n"
        "Args:\n"
        "  query (str): A natural-language query describing the information to retrieve.\n"
        "  max_results (int, optional): Maximum number of search results to include. Default is 5.\n\n"
        "Returns:\n"
        "  dict: A JSON-like dictionary including Tavily's 'answer' and 'results', "
        "or an error message if the request fails.\n"
    ),
)
